services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      retries: 10
    volumes:
      - postgres-db:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:2.9.3
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
      AIRFLOW__LOGGING__LOGGING_LEVEL: INFO
      GOOGLE_APPLICATION_CREDENTIALS: /home/airflow/.config/gcloud/application_default_credentials.json
      GOOGLE_CLOUD_PROJECT: bluebikes-demand-predictor
      PYTHONPATH: /opt/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./logs:/opt/airflow/logs
      - ~/.config/gcloud:/home/airflow/.config/gcloud:ro

    ports:
      - "8081:8080"
    command: >
      bash -lc "
      pip install --no-cache-dir google-cloud-storage pandas pyarrow requests scipy &&
      airflow db migrate &&
      airflow users create --username admin --password admin --firstname admin --lastname admin --role Admin --email admin@example.com || true &&
      rm -f /opt/airflow/airflow-webserver.pid &&
      exec airflow webserver --port 8080 --host 0.0.0.0
      "


  airflow-scheduler:
      image: apache/airflow:2.9.3
      depends_on:
        airflow-webserver:
          condition: service_started
      environment:
        AIRFLOW__CORE__EXECUTOR: LocalExecutor
        AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
        AIRFLOW__CORE__LOAD_EXAMPLES: "false"
        AIRFLOW__LOGGING__LOGGING_LEVEL: INFO
        GOOGLE_APPLICATION_CREDENTIALS: /home/airflow/.config/gcloud/application_default_credentials.json
        GOOGLE_CLOUD_PROJECT: bluebikes-demand-predictor
        PYTHONPATH: /opt/airflow
      volumes:
        - ./dags:/opt/airflow/dags
        - ./src:/opt/airflow/src
        - ./logs:/opt/airflow/logs
        - ~/.config/gcloud:/home/airflow/.config/gcloud:ro
      command: >
        bash -c "pip install --no-cache-dir google-cloud-storage pandas pyarrow requests scipy && airflow scheduler"

volumes:
  postgres-db:
